config/routes.rb
Anpiman::Application.routes.draw do
  resources :anpikakunin
  post "anpikakunin/send" => "anpikakunin#new"
  post "anpikakunin/resend" => "anpikakunin#resend"
  post "anpikakunin/regist" => "anpikakunin#regist"
  post "anpikakunin/auto" => "anpikakunin#auto"
  post "anpikakunin/sousalog" => "anpikakunin#sousalog"

  post "device/regist" => "device#regist"

  resources :syain_anpis

  resources :syain_infos

end

app/models/syain_anpi.rb
class SyainAnpi < ActiveRecord::Base
  attr_accessible :genzaiti, :idouhantei, :lat, :lng, :recieveData, :recieveTime, :sousalog, :syain_info_id, :syussyabi
  acts_as_mappable
end

app/controllers/syain_anpis_controller.rb
class SyainAnpisController < ApplicationController
  # GET /syain_anpis
  # GET /syain_anpis.json
  def index
    @syain_anpis = SyainAnpi.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @syain_anpis }
    end
  end

  # GET /syain_anpis/1
  # GET /syain_anpis/1.json
  def show
    @syain_anpi = SyainAnpi.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @syain_anpi }
    end
  end

  # GET /syain_anpis/new
  # GET /syain_anpis/new.json
  def new
    @syain_anpi = SyainAnpi.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @syain_anpi }
    end
  end

  # GET /syain_anpis/1/edit
  def edit
    @syain_anpi = SyainAnpi.find(params[:id])
  end

  # POST /syain_anpis
  # POST /syain_anpis.json
  def create
    @syain_anpi = SyainAnpi.new(params[:syain_anpi])

    respond_to do |format|
      if @syain_anpi.save
        format.html { redirect_to @syain_anpi, notice: 'Syain anpi was successfully created.' }
        format.json { render json: @syain_anpi, status: :created, location: @syain_anpi }
      else
        format.html { render action: "new" }
        format.json { render json: @syain_anpi.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /syain_anpis/1
  # PUT /syain_anpis/1.json
  def update
    @syain_anpi = SyainAnpi.find(params[:id])

    respond_to do |format|
      if @syain_anpi.update_attributes(params[:syain_anpi])
        format.html { redirect_to @syain_anpi, notice: 'Syain anpi was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @syain_anpi.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /syain_anpis/1
  # DELETE /syain_anpis/1.json
  def destroy
    @syain_anpi = SyainAnpi.find(params[:id])
    @syain_anpi.destroy

    respond_to do |format|
      format.html { redirect_to syain_anpis_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/syain_anpis_helper.rb
module SyainAnpisHelper
end

app/views/syain_anpis/_form.html.erb
<%= form_for(@syain_anpi) do |f| %>
  <% if @syain_anpi.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@syain_anpi.errors.count, "error") %> prohibited this syain_anpi from being saved:</h2>

      <ul>
      <% @syain_anpi.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :syain_info_id %><br />
    <%= f.number_field :syain_info_id %>
  </div>
  <div class="field">
    <%= f.label :syussyabi %><br />
    <%= f.text_field :syussyabi %>
  </div>
  <div class="field">
    <%= f.label :lng %><br />
    <%= f.text_field :lng %>
  </div>
  <div class="field">
    <%= f.label :lat %><br />
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :genzaiti %><br />
    <%= f.text_field :genzaiti %>
  </div>
  <div class="field">
    <%= f.label :idouhantei %><br />
    <%= f.text_field :idouhantei %>
  </div>
  <div class="field">
    <%= f.label :sousalog %><br />
    <%= f.text_field :sousalog %>
  </div>
  <div class="field">
    <%= f.label :recieveTime %><br />
    <%= f.time_select :recieveTime %>
  </div>
  <div class="field">
    <%= f.label :recieveData %><br />
    <%= f.date_select :recieveData %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/syain_anpis/edit.html.erb
<h1>Editing syain_anpi</h1>

<%= render 'form' %>

<%= link_to 'Show', @syain_anpi %> |
<%= link_to 'Back', syain_anpis_path %>

app/views/syain_anpis/index.html.erb
<h1>Listing syain_anpis</h1>

<table>
  <tr>
    <th>Syain info</th>
    <th>Syussyabi</th>
    <th>Lng</th>
    <th>Lat</th>
    <th>Genzaiti</th>
    <th>Idouhantei</th>
    <th>Sousalog</th>
    <th>Recievetime</th>
    <th>Recievedata</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @syain_anpis.each do |syain_anpi| %>
  <tr>
    <td><%= syain_anpi.syain_info_id %></td>
    <td><%= syain_anpi.syussyabi %></td>
    <td><%= syain_anpi.lng %></td>
    <td><%= syain_anpi.lat %></td>
    <td><%= syain_anpi.genzaiti %></td>
    <td><%= syain_anpi.idouhantei %></td>
    <td><%= syain_anpi.sousalog %></td>
    <td><%= syain_anpi.recieveTime %></td>
    <td><%= syain_anpi.recieveData %></td>
    <td><%= link_to 'Show', syain_anpi %></td>
    <td><%= link_to 'Edit', edit_syain_anpi_path(syain_anpi) %></td>
    <td><%= link_to 'Destroy', syain_anpi, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Syain anpi', new_syain_anpi_path %>

app/views/syain_anpis/new.html.erb
<h1>New syain_anpi</h1>

<%= render 'form' %>

<%= link_to 'Back', syain_anpis_path %>

app/views/syain_anpis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Syain info:</b>
  <%= @syain_anpi.syain_info_id %>
</p>

<p>
  <b>Syussyabi:</b>
  <%= @syain_anpi.syussyabi %>
</p>

<p>
  <b>Lng:</b>
  <%= @syain_anpi.lng %>
</p>

<p>
  <b>Lat:</b>
  <%= @syain_anpi.lat %>
</p>

<p>
  <b>Genzaiti:</b>
  <%= @syain_anpi.genzaiti %>
</p>

<p>
  <b>Idouhantei:</b>
  <%= @syain_anpi.idouhantei %>
</p>

<p>
  <b>Sousalog:</b>
  <%= @syain_anpi.sousalog %>
</p>

<p>
  <b>Recievetime:</b>
  <%= @syain_anpi.recieveTime %>
</p>

<p>
  <b>Recievedata:</b>
  <%= @syain_anpi.recieveData %>
</p>


<%= link_to 'Edit', edit_syain_anpi_path(@syain_anpi) %> |
<%= link_to 'Back', syain_anpis_path %>