config/routes.rb
Anpiman::Application.routes.draw do
  resources :anpikakunin
  post "anpikakunin/send" => "anpikakunin#new"
  post "anpikakunin/resend" => "anpikakunin#resend"
  post "anpikakunin/regist" => "anpikakunin#regist"
  post "anpikakunin/auto" => "anpikakunin#auto"
  post "anpikakunin/sousalog" => "anpikakunin#sousalog"

  post "device/regist" => "device#regist"

  resources :syain_anpis

  resources :syain_infos

end

app/models/syain_info.rb
class SyainInfo < ActiveRecord::Base
  attr_accessible :busyo, :deviceID, :name, :syainID, :syainanpi_id, :zyuusyo
end

app/controllers/syain_infos_controller.rb
class SyainInfosController < ApplicationController
  # GET /syain_infos
  # GET /syain_infos.json
  def index
    @syain_infos = SyainInfo.all
    @syain_anpis = SyainAnpi.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @syain_infos }
    end
  end

  # GET /syain_infos/1
  # GET /syain_infos/1.json
  def show
    @syain_info = SyainInfo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @syain_info }
    end
  end

  # GET /syain_infos/new
  # GET /syain_infos/new.json
  def new
    @syain_info = SyainInfo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @syain_info }
    end
  end

  # GET /syain_infos/1/edit
  def edit
    @syain_info = SyainInfo.find(params[:id])
  end

  # POST /syain_infos
  # POST /syain_infos.json
  def create
    @syain_info = SyainInfo.new(params[:syain_info])

    respond_to do |format|
      if @syain_info.save
        format.html { redirect_to @syain_info, notice: 'Syain info was successfully created.' }
        format.json { render json: @syain_info, status: :created, location: @syain_info }
      else
        format.html { render action: "new" }
        format.json { render json: @syain_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /syain_infos/1
  # PUT /syain_infos/1.json
  def update
    @syain_info = SyainInfo.find(params[:id])

    respond_to do |format|
      if @syain_info.update_attributes(params[:syain_info])
        format.html { redirect_to @syain_info, notice: 'Syain info was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @syain_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /syain_infos/1
  # DELETE /syain_infos/1.json
  def destroy
    @syain_info = SyainInfo.find(params[:id])
    @syain_info.destroy

    respond_to do |format|
      format.html { redirect_to syain_infos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/syain_infos_helper.rb
module SyainInfosHelper
end

app/views/syain_infos/_form.html.erb
<%= form_for(@syain_info) do |f| %>
  <% if @syain_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@syain_info.errors.count, "error") %> prohibited this syain_info from being saved:</h2>

      <ul>
      <% @syain_info.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :syainID %><br />
    <%= f.text_field :syainID %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :busyo %><br />
    <%= f.text_field :busyo %>
  </div>
  <div class="field">
    <%= f.label :zyuusyo %><br />
    <%= f.text_field :zyuusyo %>
  </div>
  <div class="field">
    <%= f.label :deviceID %><br />
    <%= f.text_area :deviceID %>
  </div>
  <div class="field">
    <%= f.label :syainanpi_id %><br />
    <%= f.number_field :syainanpi_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/syain_infos/edit.html.erb
<h1>Editing syain_info</h1>

<%= render 'form' %>

<%= link_to 'Show', @syain_info %> |
<%= link_to 'Back', syain_infos_path %>

app/views/syain_infos/index.html.erb
<h1>安否確認し太郎くん</h1>
- 安否確認システムv001 -
</br>
<br/>
<form id="frmDataConnectPost" action="http://shiitakeo.com:3000/anpikakunin/send" method="post" >
    <input type="submit" id="send" value="かわいい社員達へ安否確認を送信する" />
  </form>
<form id="frmDataConnectPost" action="http://shiitakeo.com:3000/anpikakunin/resend" method="post" >
    <input type="submit" id="send" value="返信をしない社畜のなりそこない共へ安否確認を再送信する" />
  </form>
  </br>
<table border = "5">
  <tr>
    <th>社員ID</th>
    <th>名前</th>
    <th>デバイス登録</th>
    <th>所属部署</th>
    <th>住所</th>
    <th>出社可能日(1-4)</th>
    <th>現在地</th>
    <th>移動判定</th>
    <th>操作履歴</th>
    <th>返信日</th>
    <th>返信時間</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @syain_infos.each do |syain_info| %>
  <%puts syain_info.syainID%>
  <% if SyainAnpi.find_by_syain_info_id(syain_info.syainID).nil? 
    anpi = SyainAnpi.new
    anpi.syussyabi = 0
    else
      anpi = SyainAnpi.find_by_syain_info_id(syain_info.syainID)
    end
    if syain_info.deviceID.empty?
      isDevice = " x "
    else
      isDevice = " o "
    end
    
    case anpi.syussyabi
    when "1"
      syussyabi = "即日可能"
    when "2"
      syussyabi = "明日可能"
    when "3"
      syussyabi = "３日程度"
    when "4"
      syussyabi = "未定"
    else
      syussyabi = " "
    end

    if anpi.sousalog === "1"
      sousalog = "操作あり"
    else
      sousalog = "操作なし"
    end
  %>
  <tr>
    <td><%= syain_info.syainID %></td>
    <td><%= syain_info.name %></td>
    <td><%= isDevice %></td>
    <td><%= syain_info.busyo %></td>
    <td><%= syain_info.zyuusyo %></td>
    <td><%= syussyabi %>
    <td><%= anpi.genzaiti %></td>
    <td><%= anpi.idouhantei%></td>
    <td><%= sousalog%></td>
    <td><%= anpi.recieveData%></td>
    <td><%= anpi.recieveTime%></td>
    <td><%= link_to '詳細', syain_info %></td>
    <td><%= link_to '編集', edit_syain_info_path(syain_info) %></td>
    <td><%= link_to '削除', syain_info, method: :delete, data: { confirm: '本当にいいですか?' } %></td>
  </tr>
<% end %>
</table>

<br />
<br/>
<%= link_to '新規社員生産', new_syain_info_path %>

app/views/syain_infos/new.html.erb
<h1>New syain_info</h1>

<%= render 'form' %>

<%= link_to 'Back', syain_infos_path %>

app/views/syain_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Syainid:</b>
  <%= @syain_info.syainID %>
</p>

<p>
  <b>Name:</b>
  <%= @syain_info.name %>
</p>

<p>
  <b>Busyo:</b>
  <%= @syain_info.busyo %>
</p>

<p>
  <b>Zyuusyo:</b>
  <%= @syain_info.zyuusyo %>
</p>

<p>
  <b>Deviceid:</b>
  <%= @syain_info.deviceID %>
</p>

<p>
  <b>Syainanpi:</b>
  <%= @syain_info.syainanpi_id %>
</p>


<%= link_to 'Edit', edit_syain_info_path(@syain_info) %> |
<%= link_to 'Back', syain_infos_path %>